[project]
name = "ca"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.4.7",
    "pyyaml>=6.0.2",
    "torch>=2.6.0",
    "transformers>=4.50.0",
]
